import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";

const port = 8791;
const base = `http://127.0.0.1:${port}/api`;
const mutableFiles = ["conversations.json", "conversation_feedback.json", "handoffs.json", "execution_logs.json", "evaluation_runs.json", "evaluation_case_runs.json", "bad_case_evaluation_cases.json", "security_events.json", "knowledge_documents.json", "knowledge_chunks.json", "knowledge_import_jobs.json", "tool_test_logs.json", "coze_sessions.json", "tools.json", "skills.json", "plans.json", "skill_versions.json", "tool_versions.json", "planner_versions.json", "llm_config.json", "token_monitor_config.json"];
const backups = new Map(await Promise.all(mutableFiles.map(async (name) => [name, await readFile(new URL(`../data/${name}`, import.meta.url), "utf8")])));
const child = spawn(process.execPath, ["server/local-server.mjs"], { cwd: new URL("../", import.meta.url), env: { ...process.env, API_PORT: String(port), COZE_API_TOKEN: "", COZE_MOCK_MODE: "true", LLM_PROVIDER: "classroom-fixture", LLM_API_KEY: "", LLM_MODEL: "" }, stdio: ["ignore", "pipe", "pipe"] });
const request = async (path, options) => {
  const response = await fetch(`${base}${path}`, options);
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || `HTTP ${response.status}`);
  return result;
};

try {
  let ready = false;
  for (let attempt = 0; attempt < 100; attempt += 1) {
    try { ready = (await request("/health")).ok; if (ready) break; } catch { await new Promise((resolve) => setTimeout(resolve, 100)); }
  }
  assert.equal(ready, true);
  const health = await request("/health");
  assert.equal(health.version, "1.6.0");
  assert.equal(health.llm_configured, true);
  assert.equal(health.llm_provider, "classroom-fixture");
  assert.equal(health.llm_model, "deterministic-onboarding-fixture");
  assert.equal(health.llm_model_source, "fixture");
  const managedSkills = (await request("/skills")).data;
  const managedTools = (await request("/tools")).data;
  const managedPlanner = (await request("/planner")).data;
  const managedLlm = (await request("/llm-config")).data;
  assert.ok(managedSkills.some((item) => item.id === "question_structuring" && item.effective_model === "deterministic-onboarding-fixture"));
  assert.ok(managedTools.some((item) => item.id === "employee_lookup"));
  assert.equal(managedPlanner.planner.id, "default_onboarding_plan");
  assert.equal(managedLlm.api_key.configured, false);
  assert.doesNotMatch(JSON.stringify(managedLlm), /Bearer |pat_[A-Za-z0-9]{10,}/);
  const unconfiguredOpenAi = (await request("/llm-config/switch", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ profile_id: "openai" }) })).data;
  assert.equal(unconfiguredOpenAi.provider, "openai-compatible");
  assert.equal(unconfiguredOpenAi.configured, false);
  const unconfiguredRunResponse = await fetch(`${base}/execute`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employee_id: "E001", actor_employee_id: "E001", question: "Provider 切换验收" }) });
  const unconfiguredRun = await unconfiguredRunResponse.json();
  assert.equal(unconfiguredRunResponse.ok, false);
  assert.equal(unconfiguredRun.code, "LLM_NOT_CONFIGURED");
  assert.ok(unconfiguredRun.run_id);
  assert.equal((await request(`/runs/${unconfiguredRun.run_id}`)).provider, "openai-compatible");
  const fixtureSwitch = (await request("/llm-config/switch", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ profile_id: "classroom-fixture" }) })).data;
  assert.equal(fixtureSwitch.provider, "classroom-fixture");
  assert.equal(fixtureSwitch.configured, true);
  const plannerPreview = (await request("/planner/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: "我需要准备哪些入职材料？", force_rules: true }) })).data;
  assert.equal(plannerPreview.validation.valid, true);
  assert.ok(plannerPreview.plan.selected_tools.includes("material_lookup"));
  const invalidPreview = (await request("/planner/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: "我需要准备哪些入职材料？", force_rules: true, disabled_tools: ["material_lookup"] }) })).data;
  assert.equal(invalidPreview.validation.valid, false);
  assert.ok(invalidPreview.validation.errors.some((item) => item.code === "MANDATORY_CAPABILITY_MISSING" || item.code === "MATERIAL_TOOL_MISSING"));
  const bootstrap = await request("/bootstrap");
  assert.ok(bootstrap.plans.length > 0);
  assert.ok(bootstrap.tools.some((tool) => tool.id === "run_coze_workflow_7659350798523416603"));
  assert.equal(bootstrap.llm.configured, true);
  assert.equal(bootstrap.llm.provider, "classroom-fixture");
  assert.ok(bootstrap.skills.every((skill) => skill.effective_model === "deterministic-onboarding-fixture" && skill.model_source === "fixture"));
  assert.equal(bootstrap.evaluation_cases.length, 100);
  assert.ok(bootstrap.bad_case_evaluation_cases.length >= 30);
  assert.ok(bootstrap.tools.some((tool) => tool.id === "knowledge_lookup"));
  assert.ok(Array.isArray(bootstrap.conversations));
  assert.ok(bootstrap.knowledge_documents.length >= 6);
  assert.equal(bootstrap.knowledge_stats.active, bootstrap.knowledge_documents.filter((item) => item.status === "active").length);
  assert.ok(Array.isArray(bootstrap.conversation_feedback));
  assert.ok(Array.isArray(bootstrap.security_events));
  assert.ok(bootstrap.analytics);
  assert.ok(bootstrap.analytics.token_usage);
  assert.equal(typeof bootstrap.analytics.token_usage.config.daily_budget_tokens, "number");
  const tokenAnalytics = await request("/analytics?days=7&source=all");
  assert.equal(tokenAnalytics.token_usage.range_days, 7);
  assert.ok(Array.isArray(tokenAnalytics.token_usage.daily));
  const tokenConfig = await request("/token-monitor/config");
  assert.ok(Array.isArray(tokenConfig.model_pricing));
  const updatedTokenConfig = await request("/token-monitor/config", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...tokenConfig, daily_budget_tokens: 100000, monthly_budget_tokens: 2000000, model_pricing: [] }) });
  assert.equal(updatedTokenConfig.daily_budget_tokens, 100000);
  const demoBootstrap = await request("/demo/bootstrap?employee_id=E001");
  assert.equal(demoBootstrap.employee.id, "E001");
  assert.equal(demoBootstrap.sample_messages.length, 4);
  assert.match(demoBootstrap.sample_messages[1].content, /林晓雨/);
  assert.match(demoBootstrap.sample_messages[3].content, /周明远/);
  const llmTest = await request("/llm/test", { method: "POST" });
  assert.equal(llmTest.ok, true);
  assert.equal(llmTest.mode, "fixture");

  const firstTurn = await request("/execute", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employee_id: "E001", actor_employee_id: "E001", question: "我的直属领导是谁？" }) });
  assert.ok(firstTurn.conversation_id);
  assert.ok(firstTurn.response_message_id);
  assert.equal(firstTurn.status, "success");
  assert.equal(firstTurn.provider, "classroom-fixture");
  assert.equal(firstTurn.model, "deterministic-onboarding-fixture");
  assert.equal(firstTurn.plan_validation.valid, true);
  assert.equal(firstTurn.plan.route_decision.type, "employee_data");
  assert.ok(firstTurn.evidence.length > 0);
  assert.equal(firstTurn.token_usage.usage_source, "fixture");
  assert.equal(firstTurn.token_usage.billable, false);
  const runDetail = await request(`/runs/${firstTurn.id}`);
  assert.equal(runDetail.id, firstTurn.id);
  const explanation = await request("/explain", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ run_id: firstTurn.id }) });
  assert.equal(explanation.run_id, firstTurn.id);
  const annotation = await request(`/runs/${firstTurn.id}/annotate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ tags: ["API smoke"], issue: "自动化标注" }) });
  assert.equal(annotation.annotation.tags[0], "API smoke");
  const runs = await request("/runs?limit=5&status=success");
  assert.ok(runs.items.some((item) => item.id === firstTurn.id));
  const streamResponse = await fetch(`${base}/agent/run`, { method: "POST", headers: { "Content-Type": "application/json", Accept: "text/event-stream" }, body: JSON.stringify({ employee_id: "E001", actor_employee_id: "E001", question: "几点下班？", source: "workbench" }) });
  const streamText = await streamResponse.text();
  assert.match(streamText, /event: plan\.created/);
  assert.match(streamText, /event: step\.completed/);
  assert.match(streamText, /event: run\.completed/);

  await request("/skills/risk_review", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: false }) });
  const blockedRun = await request("/execute", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employee_id: "E001", actor_employee_id: "E001", question: "我有劳动合同争议" }) });
  assert.equal(blockedRun.status, "blocked");
  assert.equal(blockedRun.plan_validation.valid, false);
  assert.ok(blockedRun.plan_validation.errors.some((item) => item.code === "MANDATORY_CAPABILITY_MISSING" || item.code === "RISK_REVIEW_MISSING"));
  await request("/skills/risk_review", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ enabled: true }) });
  const riskVersions = (await request("/skills/risk_review/versions")).data;
  assert.ok(riskVersions.length >= 2);
  const feedback = await request(`/conversations/${firstTurn.conversation_id}/feedback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message_id: firstTurn.response_message_id, rating: "up", tags: ["回答有帮助"] }) });
  assert.equal(feedback.rating, "up");
  const secondTurn = await request(`/conversations/${firstTurn.conversation_id}/messages`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ actor_employee_id: "E001", question: "那 HR 对接人是谁？" }) });
  assert.equal(secondTurn.conversation_id, firstTurn.conversation_id);
  await assert.rejects(() => request("/execute", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employee_id: "E001", actor_employee_id: "E002", question: "查看入职信息" }) }), /只能访问本人/);
  await request("/execute", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employee_id: "E001", actor_employee_id: "E001", question: "我的工资是多少？" }) });
  const afterSensitive = await request("/bootstrap");
  assert.ok(afterSensitive.handoffs.some((item) => item.status === "open"));
  assert.ok(afterSensitive.security_events.some((item) => item.risk_level === "high"));
  const manualHandoff = await request(`/conversations/${firstTurn.conversation_id}/handoff`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reason: "API smoke" }) });
  assert.equal(manualHandoff.source, "manual_conversation");
  const knowledge = await request("/knowledge-documents", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: "量子欢迎礼包说明", category: "福利制度", version: "1.0", effective_date: "2026-07-17", source_file: "smoke.md", keywords: ["量子欢迎礼包"], content: "量子欢迎礼包仅用于自动化测试，员工可在入职第一个工作日联系 HR 领取。" }) });
  const knowledgeAnswer = await request("/execute", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employee_id: "E001", actor_employee_id: "E001", question: "量子欢迎礼包怎么领取？" }) });
  assert.ok(knowledgeAnswer.evidence.some((item) => item.source === "knowledge_documents.json" && item.source_id === knowledge.id));
  await request(`/knowledge-documents/${knowledge.id}`, { method: "DELETE" });
  const uploadedText = "# 远程办公试行说明\n\n## 申请时间\n远程办公申请需要提前两个工作日提交，并由直属领导确认。";
  const uploaded = await request("/knowledge-files", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ filename: "远程办公试行说明.md", size: Buffer.byteLength(uploadedText), base64: Buffer.from(uploadedText).toString("base64") }) });
  assert.equal(uploaded.document.status, "review");
  await request(`/knowledge-documents/${uploaded.document.id}/publish`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ category: "制度手册", effective_date: "2026-08-01", keywords: ["远程办公", "提前两个工作日"] }) });
  const uploadedChunks = await request(`/knowledge-documents/${uploaded.document.id}/chunks`);
  assert.ok(uploadedChunks.some((item) => item.content.includes("提前两个工作日")));
  const retrievalPreview = await request("/knowledge-search/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ query: "远程办公要提前多久申请" }) });
  assert.ok(retrievalPreview.knowledge_cards.some((item) => item.source_id === uploaded.document.id));
  await request(`/knowledge-documents/${uploaded.document.id}`, { method: "DELETE" });
  const customBadCase = await request("/evaluations/cases", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question: "自动化测试：几点下班不要返回入职流程", category: "policy", failure_mode: "答非所问", expected_any: ["policy_lookup", "risk_review"], expected_none: ["task_lookup"], expected_risk: "low" }) });
  assert.equal(customBadCase.suite, "bad_case");
  const evaluation = await request("/evaluations/run", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ limit: 3 }) });
  assert.equal(evaluation.total, 3);
  assert.equal(evaluation.passed + evaluation.failed + evaluation.review + evaluation.error, 3);
  assert.ok(evaluation.results.every((item) => item.run_id));
  assert.equal(typeof evaluation.quality_gate.passed, "boolean");
  const badCaseEvaluation = await request("/evaluations/run", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ suite: "bad_case", limit: 3 }) });
  assert.equal(badCaseEvaluation.total, 3);
  assert.equal(badCaseEvaluation.passed + badCaseEvaluation.failed + badCaseEvaluation.review + badCaseEvaluation.error, 3);
  const evalOverview = await request("/eval");
  assert.ok(evalOverview.cases.length >= 131);
  assert.ok(evalOverview.runs.some((item) => item.runId));
  const updatedEvalCase = await request(`/eval/cases/${customBadCase.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expectedKeywords: { all: ["18:00"], any: [], groups: [] }, difficulty: "hard" }) });
  assert.deepEqual(updatedEvalCase.expectedKeywords.all, ["18:00"]);
  const singleEval = await request(`/eval/cases/${customBadCase.id}/run`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ employeeId: "E001" }) });
  assert.ok(singleEval.runId);
  assert.ok(["PASS", "FAIL", "REVIEW", "ERROR"].includes(singleEval.status));
  assert.equal(singleEval.scoreResult.runId, singleEval.runId);
  const duplicatedEvalCase = await request(`/eval/cases/${customBadCase.id}/duplicate`, { method: "POST" });
  await request(`/eval/cases/${duplicatedEvalCase.id}`, { method: "DELETE" });
  const config = await request("/config/export");
  assert.equal(config.format, "peopleflow-config");
  assert.equal(config.version, 2);
  assert.ok(Array.isArray(config.knowledge_documents));
  assert.doesNotMatch(JSON.stringify(config), /pat_[A-Za-z0-9]{20,}/);

  const temporary = await request("/tools", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: "smoke_http_tool", name: "Smoke HTTP Tool", type: "http", endpoint: "https://example.com", input_schema: { query: "string" } }) });
  assert.equal(temporary.id, "smoke_http_tool");
  const duplicate = await request(`/tools/${temporary.id}/duplicate`, { method: "POST" });
  assert.match(duplicate.id, /^smoke_http_tool_copy/);
  await request(`/tools/${duplicate.id}`, { method: "DELETE" });
  await request(`/tools/${temporary.id}`, { method: "DELETE" });

  const failingTool = await request("/tools", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: "smoke_failing_tool", name: "Smoke Failing Tool", type: "http", endpoint: "http://127.0.0.1:9/unreachable", timeout_ms: 1000, input_schema: { query: "string" } }) });
  const failedResponse = await fetch(`${base}/tools/${failingTool.id}/test`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ input: { query: "故障调用测试" } }) });
  const failedPayload = await failedResponse.json();
  assert.equal(failedResponse.ok, false, JSON.stringify(failedPayload));
  assert.ok(failedPayload.error);
  await request(`/tools/${failingTool.id}`, { method: "DELETE" });

  const toolTest = await request("/tools/run_coze_workflow_7659350798523416603/test", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ input: { user_id: "E001", CONVERSATION_NAME: "E001", USER_INPUT: "入职材料" } }) });
  assert.equal(toolTest.output.status, "success");
  assert.ok(toolTest.trace.length > 0);
  console.log("API smoke test passed");
} finally {
  child.kill();
  await new Promise((resolve) => setTimeout(resolve, 80));
  await Promise.all([...backups.entries()].map(([name, content]) => writeFile(new URL(`../data/${name}`, import.meta.url), content, "utf8")));
}
